import { atomOneDark } from "react-syntax-highlighter/dist/esm/styles/hljs";

const CS_THEME = {
  ...atomOneDark,
  hljs: {
    ...atomOneDark.hljs,
    background:  "#0D1117",
    color:       "#E6EDF3",
    fontSize:    "13.5px",
    lineHeight:  "1.75",
  },
  "hljs-keyword":              { color: "#FF7B72", fontWeight: "600" },
  "hljs-built_in":             { color: "#79C0FF" },
  "hljs-type":                 { color: "#FFA657" },
  "hljs-literal":              { color: "#79C0FF" },
  "hljs-number":               { color: "#79C0FF" },
  "hljs-operator":             { color: "#FF7B72" },
  "hljs-punctuation":          { color: "#8B949E" },
  "hljs-property":             { color: "#79C0FF" },
  "hljs-regexp":               { color: "#7EE787" },
  "hljs-string":               { color: "#A5D6FF" },
  "hljs-char.escape_":         { color: "#79C0FF" },
  "hljs-subst":                { color: "#E6EDF3" },
  "hljs-symbol":               { color: "#7EE787" },
  "hljs-variable":             { color: "#FFA657" },
  "hljs-variable.language_":   { color: "#FF7B72" },
  "hljs-variable.constant_":   { color: "#79C0FF" },
  "hljs-title":                { color: "#D2A8FF", fontWeight: "600" },
  "hljs-title.class_":         { color: "#FFA657", fontWeight: "600" },
  "hljs-title.function_":      { color: "#D2A8FF" },
  "hljs-params":               { color: "#E6EDF3" },
  "hljs-comment":              { color: "#8B949E", fontStyle: "italic" },
  "hljs-doctag":               { color: "#FF7B72" },
  "hljs-meta":                 { color: "#8B949E" },
  "hljs-section":              { color: "#1F6FEB" },
  "hljs-tag":                  { color: "#7EE787" },
  "hljs-name":                 { color: "#7EE787" },
  "hljs-attr":                 { color: "#79C0FF" },
  "hljs-attribute":            { color: "#A5D6FF" },
  "hljs-selector-tag":         { color: "#7EE787" },
  "hljs-selector-class":       { color: "#FFA657" },
  "hljs-selector-id":          { color: "#1F6FEB" },
  "hljs-addition":             { color: "#7EE787", background: "#0F3D18" },
  "hljs-deletion":             { color: "#FF7B72", background: "#3B0D0C" },
};

export default CS_THEME;
